### ISSUE TITLE
SIGSEGV error on Ubuntu 

### ISSUE THREAD

**Issue by antonlukin** [xssnick/Tonutils-Proxy#9]
Hi there,
I've got this error, may be it helps you to fix.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x67bbb8]

goroutine 32549 [running]:
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).changeState(0xc0008c1d40, 0x0)
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.4.1-0.20230111070238-84e56fb29fc5/adnl/dht/node.go:94 +0xb8
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).checkPing(0xc0008c1d40, {0x7b7148, 0xc000be1ec0})
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.4.1-0.20230111070238-84e56fb29fc5/adnl/dht/node.go:310 +0x165
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).poll(0xc0008c1d40)
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.4.1-0.20230111070238-84e56fb29fc5/adnl/dht/node.go:356 +0x54
created by github.com/xssnick/tonutils-go/adnl/dht.connectToNode
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.4.1-0.20230111070238-84e56fb29fc5/adnl/dht/node.go:62 +0x24a
```

**Comment by xssnick** [comment]
Hi, thank you, this is fixed in the new tonutils-go already, i'll update the proxy.
